langs = ['Python',
                 'Java',
                 'C++',
                'TypeScript',
                'JavaScript',
                'PHP',
                'Go',
                'C',
                'Ruby',
                'C#',
                'Shell',
                'Rust',
                'Scala',
                'Kotlin',
                'Swift',
                'Nix',
                'Perl',
                'Lua',
                'Groovy',
                'Dart',
                'Objective-C',
                'Haskell',
                'Emacs Lisp',
                'R',
                'Vim Script',
                'CSS',
                'HTML',
                'Fortran',
                'OCaml',
                'MATLAB']